name: publish

on:
  push:
    tags: 'v*'
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Setup Nuget
        uses: Nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore Nuget Package
        run: nuget restore fuworktimer.sln

      - name: Build
        run: dotnet publish --sc -o gh

      - name: Archive
        run: cp gh\fuworktimer.exe .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: fuworktimer.exe
        
