name: publish

on:
  push:
    tags: 'v*'
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Set culture to ja-JP
        run: |
          Set-Culture ja-JP

      - name: Build
        run: dotnet publish --property:PublishDir=gh --no-self-contained

      - name: Archive
        run: cp gh\fuworktimer.exe .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: fuworktimer.exe
        
