name: publish

on:
  push:
    tags: 'v*'
    
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2

      - name: Setup Nuget
        uses: Nuget/setup-nuget@v2
        with:
          nuget-version: 'latest'

      - name: Restore Nuget Package
        run: nuget restore fuworktimer.sln

      - name: Build
        run: msbuild fuworktimer.csproj /p:Configuration=Release /p:Platform="Any CPU" /p:PublishProfile="Properties\PublishProfiles\FloderProfile1.pubxml"

      - name: Archive
        run: cp "bin\Any CPU\Release\net9.0-windows\fuworktimer.exe" .

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: fuworktimer.exe
        
